export const PRESENCE_HEARTBEAT_INTERVAL_MS = 15_000;
export const PRESENCE_EXPIRY_BUFFER_MS = 30_000;

export const EDIT_SESSION_HEARTBEAT_INTERVAL_MS = 10_000;
export const EDIT_SESSION_EXPIRY_BUFFER_MS = 30_000;

export const SSE_PING_INTERVAL_MS = 25_000;

export const COMMENTS_PAGE_SIZE = 50;
export const HISTORY_PAGE_SIZE = 50;
export const VERSIONS_PAGE_SIZE = 20;
