"use client";
import { FormEvent, useState } from "react";
import { MessageSquare, Check, RotateCcw } from "lucide-react";
import { useCollaborationComments } from "@/lib/client/collaboration-comments";
export function CollaborationCommentsPanel({ budgetId, entityType, entityId, canComment }: { budgetId: string; entityType: string; entityId: string; canComment: boolean }) {
  const { comments, loading, error, create, resolve } = useCollaborationComments({ budgetId, entityType, entityId });
  const [body, setBody] = useState(""); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!body.trim() || pending) return; setPending(true); try { await create({ body: body.trim() }); setBody(""); } finally { setPending(false); } }
  return <section aria-label="Comentarios de colaboración" className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-4 flex items-center gap-2"><MessageSquare className="h-4 w-4 text-blue-600" /><h2 className="text-sm font-semibold text-slate-900">Comentarios</h2></div>{loading ? <p className="text-sm text-slate-500" aria-live="polite">Cargando comentarios…</p> : error ? <p role="alert" className="text-sm text-red-600">{error}</p> : <div className="space-y-3">{comments.length === 0 ? <p className="text-sm text-slate-500">Aún no hay comentarios.</p> : comments.map((comment) => <article key={comment.id} className={`rounded-xl border p-3 ${comment.resolvedAt ? "border-emerald-200 bg-emerald-50/50" : "border-slate-200"}`}><div className="flex justify-between gap-3"><p className="text-xs font-medium text-slate-700">{comment.createdByName}</p>{canComment && <button type="button" className="text-xs text-blue-600" onClick={() => void resolve(comment.id, !comment.resolvedAt)}>{comment.resolvedAt ? <><RotateCcw className="mr-1 inline h-3 w-3" />Reabrir</> : <><Check className="mr-1 inline h-3 w-3" />Resolver</>}</button>}</div><p className="mt-1 whitespace-pre-wrap text-sm text-slate-800">{comment.body}</p>{comment.parentCommentId && <p className="mt-1 text-xs text-slate-500">Respuesta</p>}</article>)}</div>}{canComment && <form onSubmit={submit} className="mt-4 space-y-2"><label htmlFor="collaboration-comment" className="sr-only">Nuevo comentario</label><textarea id="collaboration-comment" aria-label="Nuevo comentario" value={body} onChange={(event) => setBody(event.target.value)} maxLength={10000} rows={3} className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="Añade contexto para tu equipo…" /><button type="submit" disabled={pending || !body.trim()} className="rounded-xl bg-blue-600 px-3 py-2 text-sm font-medium text-white disabled:opacity-50">{pending ? "Guardando…" : "Comentar"}</button></form>}</section>;
}
