ALTER TABLE "UserSettings"
ADD COLUMN "defaultIgvRate" DECIMAL(10,4) NOT NULL DEFAULT 0.18,
ADD COLUMN "defaultGeneralExpensesRate" DECIMAL(10,4) NOT NULL DEFAULT 0.10,
ADD COLUMN "defaultUtilityRate" DECIMAL(10,4) NOT NULL DEFAULT 0.08;
