import { Check } from "lucide-react";
import { AcquisitionCta } from "@/components/landing/acquisition/acquisition-cta";
import { acquisitionOffers } from "@/components/landing/acquisition/acquisition-landing-content";
import { pricingPlans } from "@/components/landing/landing-content";

const starterPlan = pricingPlans[0];

export function AcquisitionOffersSection() {
  const offer = acquisitionOffers[0];
  return <section id="planes" className="scroll-mt-24 bg-slate-50 py-20 md:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><span className="inline-flex rounded-full border border-blue-100 bg-blue-50 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">Empieza gratis</span><h2 className="mt-4 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">Todo lo necesario para comenzar a presupuestar.</h2><p className="mt-4 text-base leading-7 text-slate-600">Crea tu cuenta gratis y trabaja con un presupuesto real. Cuando necesites más automatización, IA o capacidad para equipos, podrás ampliar tu plan.</p></div><article className="relative mx-auto mt-12 max-w-2xl overflow-hidden rounded-[1.9rem] border border-blue-200 bg-slate-950 p-8 text-white shadow-xl shadow-blue-950/10"><div className="absolute inset-x-0 top-0 h-24 bg-[radial-gradient(circle_at_top_left,rgba(56,189,248,0.18),transparent_58%)]" /><div className="relative flex items-start justify-between gap-3"><div><div className="flex items-center gap-3"><span className="inline-flex h-10 w-10 items-center justify-center rounded-2xl bg-white/10 text-sm font-semibold text-sky-300">01</span><p className="font-display text-sm font-semibold uppercase tracking-[0.18em] text-sky-300">{offer.name}</p></div><span className="mt-4 inline-flex rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-200">Gratis para empezar</span><p className="mt-4 text-sm text-slate-300">{offer.description}</p><p className="font-display mt-3 text-[2.7rem] font-semibold tracking-tight">{starterPlan.price}</p><p className="mt-1 text-sm text-slate-400">con límites operativos claros</p></div><span className="rounded-full border border-blue-400/30 bg-blue-500/15 px-3 py-1 text-xs font-semibold text-sky-200">Recomendado</span></div><div className="relative mt-6 rounded-[1.35rem] border border-white/10 bg-white/5 px-4 py-4"><p className="text-sm leading-7 text-slate-200">{starterPlan.description}</p><p className="mt-3 text-sm text-slate-400">Trabaja con presupuesto, APU manual y fórmula base sin quedar en modo demo.</p></div><div className="relative mt-8 space-y-3">{starterPlan.features.map((feature) => <div key={feature} className="flex items-start gap-3"><span className="mt-0.5 inline-flex h-5 w-5 items-center justify-center rounded-full bg-white/10 text-sky-300"><Check className="h-3.5 w-3.5" /></span><span className="text-sm leading-7 text-slate-200">{feature}</span></div>)}</div><AcquisitionCta href={offer.href} location="acquisition_offer_starter" className="relative mt-8 w-full">{offer.cta}</AcquisitionCta></article><p className="mx-auto mt-8 max-w-2xl text-center text-sm leading-6 text-slate-500">Más adelante, Pro suma Khipu IA, automatizaciones, colaboración y entregables avanzados para operaciones con mayores necesidades.</p></div></section>;
}
