"use client";
import { useState } from "react";
import { IntegrationPreviewTable } from "./integration-preview-table";
type Session = { id: string; status: string; confirmationToken?: string | null; requestId: string; counts?: { total?: number; conflicts?: number } | null; preview?: { rows?: Array<{ externalKey: string; action: string; description?: string; conflict?: string }> } | null };
export function IntegrationSessionPanel({ budgetId, session, canApply, onRefresh }: { budgetId: string; session: Session; canApply: boolean; onRefresh?: () => void }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function rollback() { setBusy(true); try { const response = await fetch(`/api/budgets/${budgetId}/integrations/sessions/${session.id}/rollback`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ requestId: `${session.id}:rollback` }) }); if (!response.ok) throw new Error("No se pudo revertir la sesión"); setMessage("Sesión revertida"); onRefresh?.(); } catch (error) { setMessage(error instanceof Error ? error.message : "Error"); } finally { setBusy(false); } }
  return <section aria-label="Sesión de integración" className="space-y-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wide text-slate-500">Sesión controlada</p><h2 className="text-base font-semibold text-slate-900">{session.status}</h2></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-700">{session.counts?.total ?? 0} registros</span></div>{session.counts?.conflicts ? <p className="text-sm text-red-600">Hay {session.counts.conflicts} conflictos que deben resolverse.</p> : null}{session.preview?.rows ? <IntegrationPreviewTable rows={session.preview.rows} /> : null}<p className="text-xs text-slate-500">La preview y las sugerencias no modifican automáticamente el presupuesto.</p>{canApply && session.status === "APPLIED" && <button type="button" onClick={() => void rollback()} disabled={busy} className="rounded-xl border border-red-200 px-3 py-2 text-sm text-red-700 disabled:opacity-50">{busy ? "Revirtiendo…" : "Rollback"}</button>}{message && <p role="status" className="text-sm text-slate-600">{message}</p>}</section>;
}
