import type { MetradoFormulaRecord } from "@/types/metrado";

export const customMetradoFormulaSuggestions: MetradoFormulaRecord[] = [
  {
    id: "suggestion-generic-area",
    templateId: "custom-suggestions",
    key: "suggestion-generic-area",
    label: "Area generica",
    category: "Generico",
    expression: "largo * ancho",
    requiredInputs: ["largo", "ancho"],
    resultUnit: "m2",
    source: "suggestion",
  },
  {
    id: "suggestion-generic-volume",
    templateId: "custom-suggestions",
    key: "suggestion-generic-volume",
    label: "Volumen generico",
    category: "Generico",
    expression: "largo * ancho * alto",
    requiredInputs: ["largo", "ancho", "alto"],
    resultUnit: "m3",
    source: "suggestion",
  },
  {
    id: "suggestion-generic-length",
    templateId: "custom-suggestions",
    key: "suggestion-generic-length",
    label: "Longitud generica",
    category: "Generico",
    expression: "longitud",
    requiredInputs: ["longitud"],
    resultUnit: "m",
    source: "suggestion",
  },
  {
    id: "suggestion-generic-quantity",
    templateId: "custom-suggestions",
    key: "suggestion-generic-quantity",
    label: "Cantidad manual",
    category: "Generico",
    expression: "cantidad",
    requiredInputs: ["cantidad"],
    resultUnit: "und",
    source: "suggestion",
  },
  {
    id: "suggestion-generic-weight",
    templateId: "custom-suggestions",
    key: "suggestion-generic-weight",
    label: "Peso generico",
    category: "Generico",
    expression: "peso",
    requiredInputs: ["peso"],
    resultUnit: "kg",
    source: "suggestion",
  },
  {
    id: "suggestion-generic-global",
    templateId: "custom-suggestions",
    key: "suggestion-generic-global",
    label: "Global generico",
    category: "Generico",
    expression: "global",
    requiredInputs: ["global"],
    resultUnit: "glb",
    source: "suggestion",
  },
  {
    id: "suggestion-wall-openings",
    templateId: "custom-suggestions",
    key: "suggestion-wall-openings",
    label: "Muro descontando vanos",
    category: "Albanileria",
    expression: "(largo * alto) - areaVanos",
    requiredInputs: ["largo", "alto", "areaVanos"],
    resultUnit: "m2",
    source: "suggestion",
  },
  {
    id: "suggestion-floor-area",
    templateId: "custom-suggestions",
    key: "suggestion-floor-area",
    label: "Area de piso",
    category: "Pisos",
    expression: "largo * ancho",
    requiredInputs: ["largo", "ancho"],
    resultUnit: "m2",
    source: "suggestion",
  },
  {
    id: "suggestion-excavation-volume",
    templateId: "custom-suggestions",
    key: "suggestion-excavation-volume",
    label: "Volumen de excavacion",
    category: "Movimiento de tierras",
    expression: "largo * ancho * profundidad",
    requiredInputs: ["largo", "ancho", "profundidad"],
    resultUnit: "m3",
    source: "suggestion",
  },
  {
    id: "suggestion-paint-coats",
    templateId: "custom-suggestions",
    key: "suggestion-paint-coats",
    label: "Pintura por manos",
    category: "Pintura",
    expression: "area * manos",
    requiredInputs: ["area", "manos"],
    resultUnit: "m2",
    source: "suggestion",
  },
  {
    id: "suggestion-pipe-length",
    templateId: "custom-suggestions",
    key: "suggestion-pipe-length",
    label: "Longitud de tuberia",
    category: "Instalaciones",
    expression: "longitud",
    requiredInputs: ["longitud"],
    resultUnit: "m",
    source: "suggestion",
  },
  {
    id: "suggestion-rebar-weight",
    templateId: "custom-suggestions",
    key: "suggestion-rebar-weight",
    label: "Peso de acero",
    category: "Acero",
    expression: "cantidad * longitud * pesoUnitario",
    requiredInputs: ["cantidad", "longitud", "pesoUnitario"],
    resultUnit: "kg",
    source: "suggestion",
  },
  // ── Linear / spatial metrado suggestions ──
  {
    id: "suggestion-linear-progresivas",
    templateId: "custom-suggestions",
    key: "suggestion-linear-progresivas",
    label: "Longitud entre progresivas",
    category: "Lineales / Espaciales",
    expression: "progresivaFin - progresivaInicio",
    requiredInputs: ["progresivaInicio", "progresivaFin"],
    resultUnit: "m",
    source: "suggestion",
  },
  {
    id: "suggestion-linear-length",
    templateId: "custom-suggestions",
    key: "suggestion-linear-length",
    label: "Longitud simple",
    category: "Lineales / Espaciales",
    expression: "longitud",
    requiredInputs: ["longitud"],
    resultUnit: "m",
    source: "suggestion",
  },
  {
    id: "suggestion-linear-longitud-cantidad",
    templateId: "custom-suggestions",
    key: "suggestion-linear-longitud-cantidad",
    label: "Longitud x cantidad",
    category: "Lineales / Espaciales",
    expression: "longitud * cantidad",
    requiredInputs: ["longitud", "cantidad"],
    resultUnit: "m",
    source: "suggestion",
  },
  // Note: Euclidean distance formulas (sqrt(x²+y²)) require ^ operator
  // which is not supported by the formula engine yet.
  // For coordinate-based calculations, users can create custom formulas
  // or use simple progressive difference: progresivaFin - progresivaInicio.
  {
    id: "suggestion-linear-tuberia-progresivas",
    templateId: "custom-suggestions",
    key: "suggestion-linear-tuberia-progresivas",
    label: "Longitud tuberia x cantidad (progresivas)",
    category: "Lineales / Espaciales",
    expression: "(progresivaFin - progresivaInicio) * cantidad",
    requiredInputs: ["progresivaInicio", "progresivaFin", "cantidad"],
    resultUnit: "m",
    source: "suggestion",
  },
];
